export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const REQUEST_SERVICE = "REQUEST_SERVICE";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const RESOLVE_AUTH_STATE = "RESOLVE_AUTH_STATE";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_COLLABORATION_USER = "UPDATE_COLLABORATION_USER";
export const SET_COLLABORATION = "SET_COLLABORATION";
export const SET_COLLABORATION_JOINED_PEOPLE =
  "SET_COLLABORATION_JOINED_PEOPLE";
export const COLLABORATION_CREATED_FROM_OFFER =
  "COLLABORATION_CREATED_FROM_OFFER";
export const SET_COLLABORATION_MESSAGES = "SET_COLLABORATION_MESSAGES";
export const RESET_COLLABORATION_MESSAGES = "RESET_COLLABORATION_MESSAGES";
export const FETCH_USER_SERVICES_SUCCESS = "FETCH_USER_SERVICES_SUCCESS";
export const FETCH_USER_MESSAGES_SUCCESS = "FETCH_USER_MESSAGES_SUCCESS";
export const MARK_MESSAGE_AS_READ = "MARK_MESSAGE_AS_READ";
export const FETCH_OFFERS_RECEIVED_SUCCESS = "FETCH_OFFERS_RECEIVED_SUCCESS";
export const FETCH_OFFERS_SENT_SUCCESS = "FETCH_OFFERS_SENT_SUCCESS";
export const RESET_LOADING = "RESET_LOADING";
export const CHANGE_OFFER_STATUS = "CHANGE_OFFER_STATUS";
